apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app
  labels:
    app: reddit-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
        - name: reddit-app
          image: gcr.io/mlops-lab7-1745391166/reddit-fastapi:v4
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
