stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - data/california_housing_train.csv
      - data/california_housing_test.csv
      - src/preprocessing.py
    params:
      - preprocessing.train_path
      - preprocessing.test_path
    outs:
      - data/preprocessing_pipeline.pkl
      - data/processed_train_features.csv
      - data/processed_test_features.csv
      - data/processed_train_target.csv
      - data/processed_test_target.csv
